export const AppColors = {
  primary: '#0070A8',
  primaryDark: '#0B1E35',
  primaryLight: '#E8F5FB',
  accent: '#00A8A8',
  accentLight: '#E8F4FB',
  background: '#F0F4F8',
  surface: '#FFFFFF',
  border: '#D8E2EC',
  textPrimary: '#0F1923',
  textSecondary: '#6B7A8D',
  textMuted: '#A8BDD0',
  success: '#059669',
  successLight: '#ECFDF5',
  warning: '#D97706',
  warningLight: '#FFFBEB',
  danger: '#DC2626',
  dangerLight: '#FEF2F2',
  info: '#2F80ED',
  infoLight: '#EAF2FE',
  sidebarText: '#A8BDD0',
  sidebarActive: '#4FC3F7',
  sidebarLogoMuted: '#5B7A95',
  sidebarProfileText: '#E0EDF5',
  loginPanelCopy: '#7B98B0',
  roleAdmin: '#7C3AED',
  roleAdminBg: '#F5F3FF',
  roleDoctor: '#1D4ED8',
  roleDoctorBg: '#EFF6FF',
  roleReceptionist: '#D97706',
  roleReceptionistBg: '#FFFBEB',
  roleTechnician: '#059669',
  roleTechnicianBg: '#ECFDF5',
  rolePatient: '#0070A8',
  rolePatientBg: '#EFF6FF',
} as const;

export type AppColor = keyof typeof AppColors;
